services:
  web:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      REDIS_URL: redis://redis:6379
      REDIS_PASSWORD: ''
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
